#!/bin/sh
if [ "Person" = "$1" ]; then
 #echo Person $2 $3 $4
 java -cp /usr/local/fort_append/lib/catch_pwd.jar:/usr/local/fort_append/lib/FortService.jar Person $2 $3 $4
elif [ "Asset" = "$1" ]; then
 #echo Asset $2 $3 $4
 java -cp /usr/local/fort_append/lib/catch_pwd.jar:/usr/local/fort_append/lib/FortService.jar Asset $2 $3 $4
elif [ "Authorization" = "$1" ]; then
 #echo Asset $2 $3 $4
 java -cp /usr/local/fort_append/lib/catch_pwd.jar:/usr/local/fort_append/lib/FortService.jar Authorization $2 $3 $4 $5 $6 $7
elif [ "Role" = "$1" ]; then
 #echo Asset $2 $3 $4
 java -cp /usr/local/fort_append/lib/catch_pwd.jar:/usr/local/fort_append/lib/FortService.jar Role $2 $3 $4
elif [ "Cmd" = "$1" ]; then
 #echo Asset $2 $3 $4
 java -cp /usr/local/fort_append/lib/catch_pwd.jar:/usr/local/fort_append/lib/FortService.jar Cmd $2
else
 echo "illegal parameter"
fi
