#!/bin/sh
### BEGIN INIT INFO
# Provides:          Sefarious
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Should-Start:      $all
# Should-Stop:       $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: FortServiceSocketApi
### END INIT INFO

start_fort_service(){
    /usr/local/fort_append/bin/StartFortService
}
stop_fort_service(){
    /usr/local/fort_append/bin/StopFortService
}
status_fort_service(){
    /usr/local/fort_append/bin/StatusFortService
}
#restart_fort_service(){
#    /usr/local/fort_append/bin/StopFortService
#    /usr/local/fort_append/bin/StartFortService
#}

case $1 in
start)
    start_fort_service
;;
stop)
    stop_fort_service
;;
status)
    status_fort_service
;;
#restart)
#    restart_fort_service
#;;
*)
    echo 'Usage:FortServiceServer start|stop|status'
;;
esac



