#!/bin/sh

FortServiceSocketApiPID=`ps -ef | grep FortServiceSocketApi | grep java | awk '{print $2}'`

if [ -z $FortServiceSocketApiPID ] ; then
  echo "FortServiceSocketApi process not exists."
else
  echo "FortServiceSocketApi process aleady exists, pid="$FortServiceSocketApiPID
fi
