#!/bin/sh
#java -cp /usr/local/fort_append/FortService/catch_pwd.jar:/usr/local/fort_append/FortService/FortService.jar Asset $1 $2 $3
#pause
if [ "Person" = $1 ]; then
 #echo Person $2 $3 $4
 java -cp /usr/local/fort_append/FortService/catch_pwd.jar:/usr/local/fort_append/FortService/FortService.jar Person $2 $3 $4
elif [ "Asset" = $1 ]; then
 #echo Asset $2 $3 $4
 java -cp /usr/local/fort_append/FortService/catch_pwd.jar:/usr/local/fort_append/FortService/FortService.jar Asset $2 $3 $4
elif [ "Authorization" = $1 ]; then
 #echo Asset $2 $3 $4
 java -cp /usr/local/fort_append/FortService/catch_pwd.jar:/usr/local/fort_append/FortService/FortService.jar Authorization $2 $3 $4 $5 $6 $7
else
 echo "illegal parameter"
fi

